### ISSUE TITLE
匠艺登陆不了，验证码坏了

### ISSUE THREAD

**Issue by chenge** [codingstyle-cn/codingstyle.cn#11]
如题。

**Comment by rckv** [comment]
```
untimeError (RuCaptcha: convert: not authorized `-' @ error/constitute.c/ReadImage/454.
convert: no images defined `png:-' @ error/convert.c/ConvertImageCommand/3046.):
  rucaptcha (0.3.1) lib/rucaptcha/captcha.rb:68:in `create'
  rucaptcha (0.3.1) lib/rucaptcha/controller_helpers.rb:13:in `generate_rucaptcha'
```

**Comment by rckv** [comment]
https://github.com/huacnlee/rucaptcha/issues/25

**Comment by rckv** [comment]
升级 ImageMagick, 6.9+ 
http://www.imagemagick.org/download/linux/CentOS/x86_64/
