### ISSUE TITLE
Exception in `find_user`

### ISSUE THREAD

**Issue by rckv** [codingstyle-cn/codingstyle.cn#9]
```
"GET /AkAk HTTP/1.0" 301 - 0.0142
F, [2016-02-23T15:18:35.165648 #12415] FATAL -- : 
Mongoid::Errors::DocumentNotFound (
message:
  Document not found for class User with attributes {:slug=>"akak"}.
summary:
  When calling User.find_by with a hash of attributes, all attributes provided must match a document in the database or this error will be raised.
resolution:
  Search for attributes that are in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil
 to be returned instead of raising this error.):
  app/models/user.rb:250:in `find_login'
  app/controllers/users_controller.rb:122:in `find_user'
```

**Comment by rckv** [comment]
Duplicated, https://github.com/codingstyle-cn/codingstyle.cn/issues/12
